// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knlovdpouxzprzdkbenh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtubG92ZHBvdXh6cHJ6ZGtiZW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3MjkyNjYsImV4cCI6MjA3NTMwNTI2Nn0.TLnpniAbM0rgZ9mmaF5wNppSg9Iv0A2kJCkxZTLmV4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});